# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 323)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color: rgb(0, 74, 153);\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 5px")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.ln_lote = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_lote.setFont(font)
        self.ln_lote.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_lote.setText("")
        self.ln_lote.setObjectName("ln_lote")
        self.gridLayout.addWidget(self.ln_lote, 3, 1, 1, 2)
        self.date_cadastro = QtWidgets.QDateEdit(Dialog)
        self.date_cadastro.setObjectName("date_cadastro")
        self.gridLayout.addWidget(self.date_cadastro, 4, 1, 1, 1)
        self.ln_num_estudo = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_num_estudo.setFont(font)
        self.ln_num_estudo.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_num_estudo.setText("")
        self.ln_num_estudo.setObjectName("ln_num_estudo")
        self.gridLayout.addWidget(self.ln_num_estudo, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.ln_codigo = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_codigo.setFont(font)
        self.ln_codigo.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_codigo.setText("")
        self.ln_codigo.setObjectName("ln_codigo")
        self.gridLayout.addWidget(self.ln_codigo, 0, 1, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chk_5dias = QtWidgets.QCheckBox(Dialog)
        self.chk_5dias.setStyleSheet("\n"
"            QCheckBox::indicator {\n"
"                border: 2px solid #797979;\n"
"                border-radius: 5px; /* Bordas arredondadas */\n"
"                width: 10px;\n"
"                height:10px;\n"
"            }\n"
"            QCheckBox::indicator:checked {\n"
"                                \n"
" background-color: #004a99; /* Cor azul quando preenchido *\n"
"            }")
        self.chk_5dias.setObjectName("chk_5dias")
        self.gridLayout_2.addWidget(self.chk_5dias, 0, 0, 1, 1)
        self.chk_15dias = QtWidgets.QCheckBox(Dialog)
        self.chk_15dias.setStyleSheet("\n"
"            QCheckBox::indicator {\n"
"                border: 2px solid #797979;\n"
"                border-radius: 5px; /* Bordas arredondadas */\n"
"                width: 10px;\n"
"                height:10px;\n"
"            }\n"
"            QCheckBox::indicator:checked {\n"
"                background-color: #004a99; /* Cor azul quando preenchido */\n"
"            }")
        self.chk_15dias.setObjectName("chk_15dias")
        self.gridLayout_2.addWidget(self.chk_15dias, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.ln_produto = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ln_produto.setFont(font)
        self.ln_produto.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; \n"
"padding: 2 5px;\n"
"")
        self.ln_produto.setText("")
        self.ln_produto.setObjectName("ln_produto")
        self.gridLayout.addWidget(self.ln_produto, 2, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 74, 153);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_cadastro = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cadastro.sizePolicy().hasHeightForWidth())
        self.btn_cadastro.setSizePolicy(sizePolicy)
        self.btn_cadastro.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cadastro.setStyleSheet("QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_cadastro.setObjectName("btn_cadastro")
        self.gridLayout_4.addWidget(self.btn_cadastro, 0, 0, 1, 1)
        self.btn_cancelar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancelar.sizePolicy().hasHeightForWidth())
        self.btn_cancelar.setSizePolicy(sizePolicy)
        self.btn_cancelar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_cancelar.setStyleSheet("QPushButton {\n"
"                border: 2px solid #b22222; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #b22222; /* fonte azul */\n"
"                padding:3px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #b22222; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.gridLayout_4.addWidget(self.btn_cancelar, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_49.setText(_translate("Dialog", "Cadastro de Amostra"))
        self.label_2.setText(_translate("Dialog", "Código:"))
        self.label_5.setText(_translate("Dialog", "Lote:"))
        self.label_6.setText(_translate("Dialog", "Data:"))
        self.chk_5dias.setText(_translate("Dialog", " 5 dias - Excursão 2 (50ºC)"))
        self.chk_15dias.setText(_translate("Dialog", " 15 dias - Excursão 1 (40ºC)"))
        self.label_4.setText(_translate("Dialog", "Produto"))
        self.label_3.setText(_translate("Dialog", "Nº de Estudo:"))
        self.label_7.setText(_translate("Dialog", "Tipo de estudo:"))
        self.btn_cadastro.setText(_translate("Dialog", "Cadastrar"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
