# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_registros.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registros(object):
    def setupUi(self, Registros):
        Registros.setObjectName("Registros")
        Registros.resize(943, 583)
        Registros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Registros)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.dateEdit = QtWidgets.QDateEdit(Registros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    color: black; /* Cor do texto do QDateEdit */\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QAbstractItemView {\n"
"    color: black; /* Cor do texto dentro do calendário */\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_12.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(Registros)
        self.label_85.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_12.addWidget(self.label_85, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Registros)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 0, 8, 1, 1)
        self.btn_busca_log = QtWidgets.QPushButton(Registros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_busca_log.sizePolicy().hasHeightForWidth())
        self.btn_busca_log.setSizePolicy(sizePolicy)
        self.btn_busca_log.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_busca_log.setFont(font)
        self.btn_busca_log.setStyleSheet("\n"
"QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding: 5px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_busca_log.setObjectName("btn_busca_log")
        self.gridLayout_12.addWidget(self.btn_busca_log, 0, 11, 1, 1)
        self.ln_buscarRegistro = QtWidgets.QLineEdit(Registros)
        self.ln_buscarRegistro.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; ")
        self.ln_buscarRegistro.setObjectName("ln_buscarRegistro")
        self.gridLayout_12.addWidget(self.ln_buscarRegistro, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 7, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(Registros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_2.sizePolicy().hasHeightForWidth())
        self.dateEdit_2.setSizePolicy(sizePolicy)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.dateEdit_2.setStyleSheet("QDateEdit {\n"
"    color: black; /* Cor do texto do QDateEdit */\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QAbstractItemView {\n"
"    color: black; /* Cor do texto dentro do calendário */\n"
"}")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_12.addWidget(self.dateEdit_2, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_63 = QtWidgets.QLabel(Registros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("")
        self.label_63.setObjectName("label_63")
        self.gridLayout_12.addWidget(self.label_63, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Registros)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 5, 1, 1)
        self.users_log = QtWidgets.QLineEdit(Registros)
        self.users_log.setMaximumSize(QtCore.QSize(120, 16777215))
        self.users_log.setStyleSheet("border: 2px solid #bababa; /* borda cinza */\n"
"border-radius: 5px; ")
        self.users_log.setObjectName("users_log")
        self.gridLayout_12.addWidget(self.users_log, 0, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 10, 1, 1)
        self.btn_exportar_log = QtWidgets.QPushButton(Registros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exportar_log.sizePolicy().hasHeightForWidth())
        self.btn_exportar_log.setSizePolicy(sizePolicy)
        self.btn_exportar_log.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_exportar_log.setFont(font)
        self.btn_exportar_log.setStyleSheet("\n"
"QPushButton {\n"
"                border: 2px solid #004a99; /* borda azul */\n"
"                border-radius: 5px; /* bordas mais quadradas */\n"
"                color: #004a99; /* fonte azul */\n"
"                padding: 5px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #004a99; /* hover azul */\n"
"                color: #ffffff; /* fonte branca */\n"
"            }")
        self.btn_exportar_log.setObjectName("btn_exportar_log")
        self.gridLayout_12.addWidget(self.btn_exportar_log, 0, 12, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.tableView_LOG = QtWidgets.QTableView(Registros)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableView_LOG.setFont(font)
        self.tableView_LOG.setStyleSheet("QTableView {\n"
"                border: 2px solid #bababa; /* Cor da borda da tabela */\n"
"                border-radius: 5px; /* Cantos arredondados da tabela */\n"
"                selection-background-color: #004a99; /* Cor de fundo da seleção */\n"
"                gridline-color: #004a99; /* Cor das linhas de grade */\n"
"            }\n"
"            QTableView::item {\n"
"                padding: 5px; /* Espaçamento interno das células */\n"
"                color: #000000; /* Cor do texto */\n"
"            }\n"
"            QHeaderView::section {\n"
"                background-color: #bababa; /* Cor de fundo dos cabeçalhos */\n"
"                color: #000000; /* Cor do texto dos cabeçalhos */\n"
"                padding: 5px; /* Espaçamento interno dos cabeçalhos */\n"
"            }")
        self.tableView_LOG.setObjectName("tableView_LOG")
        self.gridLayout.addWidget(self.tableView_LOG, 4, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(Registros)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setStyleSheet("background-color: rgb(0, 74, 153);\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 5px")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Registros)
        QtCore.QMetaObject.connectSlotsByName(Registros)

    def retranslateUi(self, Registros):
        _translate = QtCore.QCoreApplication.translate
        Registros.setWindowTitle(_translate("Registros", "Registros"))
        self.label_85.setText(_translate("Registros", "até"))
        self.label_2.setText(_translate("Registros", "Usuário:"))
        self.btn_busca_log.setText(_translate("Registros", "Buscar"))
        self.label_63.setText(_translate("Registros", "Data:"))
        self.label.setText(_translate("Registros", "Evento:"))
        self.btn_exportar_log.setText(_translate("Registros", "Exportar"))
        self.label_28.setText(_translate("Registros", "Auditoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registros = QtWidgets.QDialog()
    ui = Ui_Registros()
    ui.setupUi(Registros)
    Registros.show()
    sys.exit(app.exec_())
